### ISSUE TITLE
IDC pre-v10 testing findings

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/slim#66]
Let's keep the running list of issues here, and let @hackermd break into separate issues as he sees fit
- [x] only 17 studies have PR, while there are 25 studies that have SamplesPerPixel = 1 (excluding OHSU) - Markus will look into adding the missing PRs, may be easy to do - tracked in https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/1306
- [x] unable to zoom into slide, console reports "Failed to decode" for https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.305755249420617670925805518669597959172/series/1.3.6.1.4.1.5962.99.1.1997715167.198366244.1655560156895.4.0?state=1.2.826.0.1.3680043.10.511.3.17035072567876988874059842839281235 (per @dclunie , over-zooming is not expected, and the images from the WUSTL collection don't have high resolution) - this is expected, no action
- [x] is there a good reason to not choose one of the PRs by default and instead show the result of the heuristic? - no clear answer how to handle this, will not do for the upcoming release - tracked in https://github.com/herrmannlab/slim/issues/115
- [x] is there a good reason not to show some kind of "in progress" indicator for the mouse pointer when the data is still being loaded? There is nothing in the interface that would suggest loading is not done when loading is not done - I find that confusing - will look into this, consider mouse pointer? post-v10 - tracked in https://github.com/herrmannlab/slim/issues/117
- [x] if a study contains Label image, no images are going to be shown, error shown on top of screen, details in https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/1253#issuecomment-1167980524 - for v10, we will look into either quick fix to skip label images, or excluding those images from the release - tracked in https://github.com/herrmannlab/slim/issues/116

**Comment by hackermd** [comment]
I created the following issues in Slim to track the corresponding items of the above list:

https://github.com/herrmannlab/slim/issues/115
https://github.com/herrmannlab/slim/issues/116
https://github.com/herrmannlab/slim/issues/117

**Comment by fedorov** [comment]
When trying to open this https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.289188443974026654725116153923555879592/series/1.3.6.1.4.1.5962.99.1.1997730251.1381948079.1655560171979.4.0, I am getting "failed to decode frame", and the slide does not load completely.

**Comment by fedorov** [comment]
Is the rendering below expected? It looks somewhat pale/strange (for someone like me, who is looking for a pretty picture, anyway)

https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.63504200218356539417558724289824234398/series/1.3.6.1.4.1.5962.99.1.2336236735.1380885418.1655898678463.4.0

![image](https://user-images.githubusercontent.com/313942/177357811-7724d46a-42fb-4746-a348-aaebdd945098.png)

**Comment by fedorov** [comment]
https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.225599974078887472942035661647638662953/series/1.3.6.1.4.1.5962.99.1.2335350246.1827777996.1655897791974.4.0

![image](https://user-images.githubusercontent.com/313942/177359884-23ce54d0-786f-4dc1-8872-53f6ece68267.png)

![image](https://user-images.githubusercontent.com/313942/177359931-7d3df2d2-e047-4a22-b238-92d08caf038f.png)

**Comment by hackermd** [comment]
@fedorov the `ERR_QUIC_PROTOCOL_ERROR` seems to be specific to the Chrome browser and is probably nothing we need to worry about at this point.

**Comment by hackermd** [comment]
Re https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.63504200218356539417558724289824234398/series/1.3.6.1.4.1.5962.99.1.2336236735.1380885418.1655898678463.4.0

These images contains a few artifacts (top left) and some bright biological structures (right), which the autothreshold seems to struggle with
![Screen Shot 2022-07-05 at 1 05 05 PM](https://user-images.githubusercontent.com/6855297/177381047-358222d5-0710-4de5-be4b-c89b711796b6.png)

**Comment by hackermd** [comment]
Re https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.225599974078887472942035661647638662953/series/1.3.6.1.4.1.5962.99.1.2335350246.1827777996.1655897791974.4.0

I could reproduce the decoding issue. It appears to be only a single tile that could not be decoded. In this case, the data is not completely loaded and the cursor keeps spinning. We may need to take tile loading errors into consideration when determining whether data loading is complete.

The presentation states look fine in my opinion. There are some staining artifacts, but there is nothing we can do about that.

![Screen Shot 2022-07-05 at 1 37 38 PM](https://user-images.githubusercontent.com/6855297/177384774-f7df99ca-2a64-4579-86a3-b6c40a53a717.png)

**Comment by hackermd** [comment]
Re https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.6018351362280197054240452097367934352/series/1.3.6.1.4.1.5962.99.1.2349996087.1135814742.1655912437815.4.0?state=1.2.826.0.1.3680043.10.511.3.80854203852226740240719016918171946

> yellow (CD68 channel) seems to be saturated - not sure if this is expected

The values of interest are computed for the lowest resolution level to provide "optimal" contrast at that level. These may not be optimal for higher resolution levels and one may have to adjust the values of interest setting.

I think the presentation state looks fine for the lowest resolution level:

![Screen Shot 2022-07-05 at 1 48 07 PM](https://user-images.githubusercontent.com/6855297/177386562-25d413c2-45b8-4769-a7d6-5fb5cfc8c739.png)

**Comment by hackermd** [comment]
@fedorov I found the problem that caused the tile decoding error, fixed it in Slim release v0.9.1, and updated the dev deployment.

**Comment by fedorov** [comment]
Markus, thank you for the investigations and fixes!

**Comment by hackermd** [comment]
Thanks for reporting the issue @Gibbsdavidl. The issue is fixed in Slim version 0.9.2 and the dev deployment is updated.

**Comment by pgundluru** [comment]
The following Images show a blank screen:

https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.290373112196293767121682316470713832864/series/1.3.6.1.4.1.5962.99.1.2025795855.1687783453.1655588237583.4.0 

https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.136678376329199259039490655952038128147/series/1.3.6.1.4.1.5962.99.1.2015146741.124585992.1655577588469.4.0 

https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.155118844294092675540800503483899863510/series/1.3.6.1.4.1.5962.99.1.2027525727.229099027.1655589967455.4.0

**Comment by fedorov** [comment]
Interesting - all of those 3 links work for me.

**Comment by pgundluru** [comment]
I am testing on W10 Chrome browser and for the first image I see the below error on console with a blank image 

https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.290373112196293767121682316470713832864/series/1.3.6.1.4.1.5962.99.1.2025795855.1687783453.1655588237583.4.0

![image](https://user-images.githubusercontent.com/85526819/177818786-904b6f78-003b-47ba-9e57-4218c192e792.png)

**Comment by Gibbsdavidl** [comment]
https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.290373112196293767121682316470713832864/series/1.3.6.1.4.1.5962.99.1.2025795855.1687783453.1655588237583.4.0

Hmmmm.  Seems to be working on my W10 Chrome... Version 103.0.5060.114 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/561865/177835763-dbe925a1-df1a-4028-aab6-7ff76fafb4e1.png)

**Comment by pgundluru** [comment]
I believe its an issue with Chrome 32 bit that I was using. @fedorov has requested to ignore issues with chrome 32 bit at this time. 

![image](https://user-images.githubusercontent.com/85526819/177850373-1c859707-d023-4ae1-820c-c6d4b9878d53.png)

![image](https://user-images.githubusercontent.com/85526819/177851484-1dc4bb9c-77a9-43e3-b9a5-7895af876b3c.png)
